modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"
[[mods]]
modId="goety"
version="${mod_version}"
displayName="Goety"
displayURL="https://github.com/imbavirus/Goety-3"
logoFile="Goety.png" #optional
credits='''Tutorial/Help: GentlemanRevvnar, Technovision, Cy4's Modding, TelepathicGrunt, diesieben07.

Major Bug Testing: Mich705, pantman687, glacial_flower, Mephodio.

Several textures made by zozozrob. Several item retextures made by mongoose_artist and amyspiralvt. Necromancer Servant texture by frosty_gg. Wither Necromancer Servant texture by xby123896_88452. Brood Mother Textures by xiaowu. Void Flame Textures by emptyCoso. Piker, Conquillager, Inquillager, Maverick, Heretic remodel and base textures by luomu05. Ender Keeper's design by vulkan9346, most animations by joturtleguy21.

Blighted Shack, Graveyard, Ominous Blacksmith and Buried Ritual build by boxman. Dark Manor and Sorcerous Keep build by trufflehistorian.

Chinese Translation: NUTTAR, Player_7, Japanese Translation: SAGA, 坂上駒子, Russian Translation: .cool_nickname, Ukrainian Translation: catvasilthefirst, Polish Translation: darknetherlord, Português Translation: crougamer.exe'''
authors="Infernos"
description='''
Goety adds a bunch of new Mobs that can help or hinder players and a magic system that can provides a player a different way of combat!
'''
[[dependencies.goety]] #optional
modId="neoforge" #mandatory

mandatory=true #mandatory

versionRange="${neo_version_range}" #mandatory

ordering="NONE"

side="BOTH"

[[dependencies.goety]]
modId="curios"
mandatory=true
versionRange="[9.5.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.goety]]
modId="minecraft"

mandatory=true

versionRange="${minecraft_version_range}"

ordering="NONE"

side="BOTH"

[[mixins]]
config="goety.mixins.json"
